name: Сгенерировать релиз

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  bundle-files:
    runs-on: ubuntu-latest

    steps:
      - name: Вытянуть репозиторий
        uses: actions/checkout@v4

      - name: Скопировать общее содержимое
        run: |
          cp -r shared/. professor/
          cp -r shared/. student/

      - name: Загрузить архив профессора
        uses: actions/upload-artifact@v4
        with:
          name: professor.zip
          path: professor/
          retention-days: 5

      - name: Загрузить архив студента
        uses: actions/upload-artifact@v4
        with:
          name: student.zip
          path: student/
          retention-days: 5
