name: Сгенерировать релиз

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  bundle-files:
    runs-on: ubuntu-latest

    steps:
      - name: Вытянуть репозиторий
        uses: actions/checkout@v4

      # Создаем архив для профессора.
      # Внутри будут лежать две папки рядом: "professor" и "shared".
      - name: Загрузить архив профессора
        uses: actions/upload-artifact@v4
        with:
          name: professor_release
          path: |
            professor/
            shared/
          retention-days: 5

      # Создаем архив для студента.
      # Внутри будут лежать две папки рядом: "student" и "shared".
      - name: Загрузить архив студента
        uses: actions/upload-artifact@v4
        with:
          name: student_release
          path: |
            student/
            shared/
          retention-days: 5